name: Clone, Run Script, and Push

on:
  workflow_dispatch:

jobs:
  Clone-Run-script-Push:
    runs-on: ubuntu-latest

    steps:
    -   name: Checkout target repository
        uses: actions/checkout@v4
        with:
            repository: ronakpalsinghbali/MERN_APP_NewRelic_Test
            token: ${{ secrets.TARGET_REPO_TOKEN }}
            path: target-repo
            ref: main
    
    -   name: Verify the contents of target repo
        run: |
            echo "Current directory: $(pwd)"
            cd /home/runner/work/NewRelic_Automation_Scripts/NewRelic_Automation_Scripts/target-repo/backend
            ls -al

    -   name: Checkout current repository
        uses: actions/checkout@v4
        with:
            path: current-repo

    
    -   name: Verify the contents of current repo
        run: |
            echo "Current directory: $(pwd)"
            cd /home/runner/work/NewRelic_Automation_Scripts/NewRelic_Automation_Scripts/current-repo
            ls -al

    -   name: Copy automation.py to target repo backend
        run: |
            echo "Current directory: $(pwd)"
            cp /home/runner/work/NewRelic_Automation_Scripts/NewRelic_Automation_Scripts/current-repo/automation.py /home/runner/work/NewRelic_Automation_Scripts/NewRelic_Automation_Scripts/target-repo/backend

    -   name: Verify the contents of target repo again
        run: |
            echo "Current directory: $(pwd)"
            cd /home/runner/work/NewRelic_Automation_Scripts/NewRelic_Automation_Scripts/target-repo/backend
            ls -al

    -   name: Set up Git in target repo
        run: |
            cd target-repo
            ls -l
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
      
    # -   name: Commit and push changes to target repo
    #     run: |
    #         cd target-repo
    #         git add backend/automation.py
    #         git commit -m "Add automation.py to backend"
    #         git push origin main
    #     env:
    #         GITHUB_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}




