name: Clone, Run Script, and Push

on:
  workflow_dispatch:

jobs:
  Clone-Run-script-Push:
    runs-on: ubuntu-latest

    steps:
    -   name: Checkout the repository
        uses: actions/checkout@v2
        with:
            repository: ronakpalsinghbali/MERN_APP_NewRelic_Test
            token: ${{ secrets.TARGET_REPO_TOKEN }}
            ref: main
    
    -   name: Verify the contents of the repo
        run: |
            echo "Current directory: $(pwd)"
            cd ./backend
            ls -al

    # - name: Set up Git
    #   run: |
    #     git config --global user.name 'github-actions'
    #     git config --global user.email 'github-actions@github.com'

    # - name: Run the script
    #   run: |
    #     chmod +x ./your-script.sh
    #     ./your-script.sh

    # - name: Commit and push changes
    #   run: |
    #     git add .
    #     git commit -m "Run script and update repository"
    #     git push origin main
    #   env:
    #     REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
